version: '3'
services:
  databases:
    image: mysql
    ports:
      - "3308:3306"
    env_file:
      - evs.env    
  web:
    image: nginx    
    ports:
      - "8089:80" 
    depends_on:
      - databases
  bot:
    image: ibm    
    ports:
      - "8089:80"
